config/routes.rb
Rails.application.routes.draw do
  get 'main_menu/index'

  resources :references
  resources :types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paper.rb
class Paper < ApplicationRecord
    self.primary_key = :reference_id
    belongs_to :reference, optional: true, foreign_key: 'reference_id' 
end

app/models/reference.rb
class Reference < ApplicationRecord
    belongs_to :type, foreign_key: 'Type'
    has_one :paper
    accepts_nested_attributes_for :paper
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :references 
    accepts_nested_attributes_for :references 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_menu_controller.rb
class MainMenuController < ApplicationController
  def index
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
    @reference.build_paper
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)
    #print(reference_params[:papers_attributes])
    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:Title, :Type, paper_attributes: [:released_date, :start_page, :end_page, :publisher])
    end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_menu_helper.rb
module MainMenuHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appsample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_menu/index.html.erb
<h1>参考文献管理MainMenu</h1>

<p><%= link_to 'Reference Page', '/references/' %></p>

<p><%= link_to 'Type Page', '/types/' %></p>

app/views/references/_form.html.erb
<%= form_with(model: reference, local: true) do |form| %>
  <% if reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title, id: :reference_Title %>
  </div>

  <div class="field">
    <%= form.label :Type %>
    <%= form.collection_select(:Type, Type.all, :id, :name, {}, {:id => "reference_Type"}) %>
  </div>

    <%= form.fields_for :paper do |p| %>

      <div class="field">
        <%= p.label :released_date %>
        <%= p.text_field :released_date, id: :released_date %>
      </div>

      <div class="field">
        <%= p.label :start_page %>
        <%= p.text_field :start_page, id: :start_page %>
      </div>

      <div class="field">
        <%= p.label :end_page %>
        <%= p.text_field :end_page, id: :end_page %>
      </div>

      <div class="field">
        <%= p.label :publisher %>
        <%= p.text_field :publisher, id: :publisher %>
      </div>
    <% end %>
      
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<p>
    <%= link_to 'Show', @reference %> 
</p>
<p>
    <%= link_to 'Back', references_path %>
</p>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.Title %></td>
        <td><%= reference.type.name %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>
<p><%= link_to 'MainMenu', '/main_menu/index' %></p>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

<script>
//$("#reference_Title").prop("disabled", true);
//$("#reference_Type").prop("disabled", true);
</script>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @reference.Title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @reference.Type %>
</p>



<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>
<p><%= link_to 'MainMenu', '/main_menu/index' %></p>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>